version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres-db
    ports:
      - 5432:5432
  backend:
    image: myschool-backend-image
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=DEV
      - DEV_DATABASE_URL=postgres://root:sekret@db:5432/
    depends_on:
      - db
