/* eslint-disable */
import { Express } from 'express';
import swaggerAutogen from 'swagger-autogen';
import swaggerUI from 'swagger-ui-express';
import {
  OpenAPIRegistry,
  OpenAPIGenerator,
} from '@asteasolutions/zod-to-openapi';
// const swaggerDocument = require('./../../swagger-output.json');
import fs from 'fs';
import { ZStudentPost, ZStudentPut } from '../validator/student.validator';
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';

extendZodWithOpenApi(z);
// Zod to OpenAPI part

const registry = new OpenAPIRegistry();

// const ZStudentPostO = registry.register('ZStudentPost', ZStudentPost);
registry.register('ZStudentPost', ZStudentPost.shape.body);
// Need to fix #33 for this to work... zod-to-openapi does not support .transform
// registry.register('ZStudentFind', ZStudentFind.shape.query);
registry.register('ZStudentPut', ZStudentPut.shape.body);

const generator = new OpenAPIGenerator(registry.definitions, '3.0.0');

const components = generator.generateComponents();

// console.log('ZStudentPostOpenAPI', ZStudentPostO);
console.log('components', components.components?.schemas);

const doc = {
  info: {
    title: 'my-school-server',
    description:
      'My 4238942 try at API Docs for my-school-server, auto generated by swagger-autogen',
  },
  tags: [
    {
      name: 'login',
      description: 'login route',
    },
    {
      name: 'fees',
      description: 'fees routes',
    },
    {
      name: 'students',
      description: 'students routes',
    },
  ],
  '@definitions': components.components?.schemas,
  host: 'localhost:8080',
  schemes: ['http'],
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/app.ts'];

const startSwagger = async (app: Express) => {
  await swaggerAutogen({ openapi: '3.0.0' })(outputFile, endpointsFiles, doc);
  const specs = fs.readFileSync('./swagger-output.json', 'utf8');

  app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(JSON.parse(specs)));
};

export default startSwagger;
