/* eslint-disable */
import swaggerAutogen from 'swagger-autogen';
import {
  OpenAPIRegistry,
  OpenAPIGenerator,
} from '@asteasolutions/zod-to-openapi';
import { ZStudentPost, ZStudentPut } from '../validator/student.validator';
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';
import { ZUserLogin } from '../validator/user.validator';

extendZodWithOpenApi(z);
// Zod to OpenAPI part

const registry = new OpenAPIRegistry();

// Need to fix #33 for this to work... zod-to-openapi does not support .transform
// registry.register('ZStudentFind', ZStudentFind.shape.query);
// and similar schemas that include .transform..

// Login Schema
registry.register('ZUserLogin', ZUserLogin.shape.body);

// Student Schemas
registry.register('ZStudentPost', ZStudentPost.shape.body);
registry.register('ZStudentPut', ZStudentPut.shape.body);

// X Route Schemas...

const generator = new OpenAPIGenerator(registry.definitions, '3.0.0');

const components = generator.generateComponents();

const doc = {
  info: {
    title: 'my-school-server',
    description:
      'My 4238942 try at API Docs for my-school-server, auto generated by swagger-autogen',
  },
  '@definitions': components.components?.schemas,
  securityDefinitions: {
    cookieAuth: { type: 'apiKey', in: 'cookie', name: 'sid' },
  },
  host: 'localhost:8080',
  schemes: ['http'],
};

const outputFile = '../swagger-output.json';
const endpointsFiles = ['./src/app.ts'];

swaggerAutogen({ openapi: '3.0.0' })(outputFile, endpointsFiles, doc);
