name: Deploy to EC2 instance

# Made with the help of ChatGPT :D
# Only works on push to main branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: |
      contains(join(toJson(github.event.commits.*.message), ' '), '#skipdeploy') != true
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOSTNAME }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls
            rm -f deploy.sh
            wget https://raw.githubusercontent.com/G0maa/my-school-server/master/deploy.sh
            chmod +x deploy.sh
            ./deploy.sh
